version: 1

project_name: kubectl-usage

before:
  hooks:
    - go mod tidy

builds:
  - id: kubectl-usage
    main: .
    binary: kubectl-usage
    ldflags:
      - -s -w
      - -X main.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: AsierCaballero
    name: kubectl-usage
